# -*- coding: utf-8 -*-
"""cv_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trBlckQt71AuNUVSY5vdW58hTlv8QPhJ
"""

!pip install PyPDF2 google-generativeai

from google.colab import files

print("Upload your CV PDF file:")
uploaded = files.upload()

# Get the filename automatically
filename = list(uploaded.keys())[0]
print(f"✅ Uploaded: {filename}")

import os
import google.generativeai as genai
from google.colab import userdata

# Fetch key from Colab Secrets
api_key = userdata.get('my_key')

# Quick check before proceeding
if not api_key or api_key == "my_key":
    print("❌ API key not found. Add it to Colab Secrets first.")
else:
    os.environ["GEMINI_KEY"] = api_key
    genai.configure(api_key=api_key)
    print("✅ API key set successfully")
    print(f"   Key preview: {api_key[:8]}...")  # shows first 8 chars only

from PyPDF2 import PdfReader

reader = PdfReader(filename)
text = ""

for page in reader.pages:
    t = page.extract_text()
    if t:
        text += t + "\n"

print(f"✅ Text extracted from {len(reader.pages)} page(s)")
print("-" * 40)
print(text[:500])  # preview first 500 characters

print("Available models on your account:\n")
for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(" →", m.name)

def analyze_cv(text, choice):

    prompts = {
        "1": (
            "Contact Details",
            "Extract all contact details from this CV: "
            "phone numbers, email addresses, LinkedIn, GitHub, "
            "or any other social links. Label each one clearly."
        ),
        "2": (
            "Skills Finder",
            "List all skills mentioned in this CV. "
            "Group them into categories like: "
            "Programming Languages, Frameworks, Tools, Soft Skills."
        ),
        "3": (
            "CV Summary",
            "Give a structured summary of this CV with: "
            "Name, Current Role, Years of Experience, "
            "Top 3 Skills, Education, and a 2-sentence professional bio."
        ),
        "4": (
            "Location Finder",
            "Find all location names mentioned in this CV: "
            "cities, states, countries, colleges, companies. "
            "List each one with context (e.g. Chennai — college location)."
        ),
        "5": (
            "Keyword Search",
            None  # handled separately
        ),
    }

    if choice not in prompts:
        print("❌ Invalid choice. Enter 1 to 5.")
        return

    task_name, prompt = prompts[choice]

    # Keyword search needs extra input
    if choice == "5":
        keyword = input("Enter keyword to search: ").strip()
        prompt = (
            f'Count exactly how many times "{keyword}" appears in this CV '
            f"(case-insensitive). "
            f"Then list every line or bullet point where it appears."
        )
        task_name = f'Keyword Search — "{keyword}"'

    print(f"\n🔍 Running: {task_name}...\n")
    print("-" * 40)

    # Call Gemini API
    model = genai.GenerativeModel("gemini-2.5-flash")

    full_prompt = (
        f"{prompt}\n\n"
        f"Important: Only report what is actually present in the CV text. "
        f"Do not guess or hallucinate.\n\n"
        f"CV Text:\n{text}"
    )

    response = model.generate_content(full_prompt)

    print(f"📋 Result — {task_name}")
    print("-" * 40)
    print(response.text)
    print("-" * 40)

while True:
    print("=" * 40)
    print("       CV ANALYZER — GEMINI AI")
    print("=" * 40)
    print("1 — Contact Details")
    print("2 — Skills Finder")
    print("3 — CV Summary")
    print("4 — Location Finder")
    print("5 — Keyword Search")
    print("q — Quit")
    print("=" * 40)

    choice = input("Enter your choice (1-5 or q): ").strip()

    if choice == "q":
        print("Goodbye!")
        break

    analyze_cv(text, choice)